using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Tessera.Core.Abstractions;
using Tessera.Core.Channels;
using Tessera.Core.Resources;
using Tessera.Data;
using Tessera.Web.Services;

namespace Tessera.Web.Jobs;

// Auto-registers due recurring expenses (or sends a reminder for AutoRegister = false ones)
// and notifies the space owner — docs/01-architettura.md. "Today" is resolved per owner's
// own timezone, since RecurringExpense itself has no timezone of its own.
public sealed class RecurringExpenseJob(
    IServiceScopeFactory scopeFactory,
    IChannel channel,
    IStringLocalizer<Messages> localizer,
    ILogger<RecurringExpenseJob> logger) : IScheduledJob
{
    public string Name => "RecurringExpense";

    public TimeSpan Interval => TimeSpan.FromHours(1);

    public async Task RunAsync(CancellationToken ct)
    {
        await using var scope = scopeFactory.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<TesseraDbContext>();
        var recurringExpenses = scope.ServiceProvider.GetRequiredService<RecurringExpenseService>();
        var identities = scope.ServiceProvider.GetRequiredService<IChannelIdentityRepository>();

        var now = DateTimeOffset.UtcNow;
        var active = await recurringExpenses.GetAllActiveAsync(ct);

        foreach (var recurring in active)
        {
            var space = await db.Spaces.AsNoTracking().FirstOrDefaultAsync(x => x.Id == recurring.SpaceId, ct);
            if (space is null)
            {
                continue;
            }

            var owner = await db.DomainUsers.AsNoTracking().FirstOrDefaultAsync(u => u.Id == space.OwnerId, ct);
            var timeZone = owner?.TimeZoneId is null ? TimeZoneInfo.Utc : TimeZoneInfo.FindSystemTimeZoneById(owner.TimeZoneId);
            var today = DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(now, timeZone).Date);

            if (recurring.EndsOn is { } endsOn && endsOn < today)
            {
                continue;
            }

            if (!RecurringExpenseService.IsDue(recurring, today))
            {
                continue;
            }

            await recurringExpenses.GenerateAsync(recurring.Id, today, ct);

            if (owner is null)
            {
                continue;
            }

            var culture = new CultureInfo(owner.PreferredCulture);
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;

            var formatted = MoneyFormatter.Format(recurring.Amount, recurring.Currency, culture.Name);
            var text = recurring.AutoRegister
                ? localizer["RecurringExpenses.AutoGenerated", recurring.Description, formatted]
                : localizer["RecurringExpenses.ReminderDue", recurring.Description, formatted];

            var ownerIdentities = await identities.GetForUserAsync(owner.Id, ct);
            foreach (var identity in ownerIdentities)
            {
                if (identity.ChannelName != channel.Name || identity.ExternalChatId is not { } chatId)
                {
                    continue;
                }

                try
                {
                    await channel.SendTextAsync(new ChannelAddress(identity.ChannelName, chatId), text, ct);
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, "Failed to notify recurring expense {RecurringExpenseId} to {ChannelName}/{ChatId}",
                        recurring.Id, identity.ChannelName, chatId);
                }
            }
        }
    }
}
