<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Tessera.Core\Tessera.Core.csproj" />
    <ProjectReference Include="..\Tessera.Data\Tessera.Data.csproj" />
    <ProjectReference Include="..\Tessera.Channels\Tessera.Channels.csproj" />
    <ProjectReference Include="..\Tessera.Integrations\Tessera.Integrations.csproj" />
    <ProjectReference Include="..\Tessera.Ai\Tessera.Ai.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>141161d7-a910-42cf-bbfa-6667a1474ed6</UserSecretsId>
  </PropertyGroup>

</Project>
